index:
  path: posts
  defaults:
    _controller: App\Controller\PostController::indexAction

add:
  path: posts/add
  defaults:
    _controller: App\Controller\PostController::addAction

view:
  path: posts/view/{id}
  defaults:
    _controller: App\Controller\PostController::showAction

edit:
  path: posts/edit/{id}
  defaults:
    _controller: App\Controller\PostController::editAction

delete:
  path: posts/delete/{id}
  defaults:
    _controller: App\Controller\PostController::deleteAction
